In [ ]:
### chan 2020/11/23
import numpy as np

In [ ]:
### MSE
def loss_MSE(z_predict ,z_true):
    loss = np.mean(np.sum(np.square(y_predict-y_true),axis=-1))
    dzLast = z_predict - z_true
    return loss, dzLast

### Cross Entropy
def loss_CrossEntropy(z_predict, z_true):
    ### in order to avoid overflow, y_predict should shift to a relatively small value and this thift will not change result of softmax 
    z_exp = np.exp(z_predict - np.max(z_predict, axis=-1, keepdims=True))
    
    ### calculate softmax before using cross entropy.
    z_probability = z_exp / np.sum(z_exp, axis=-1, keepdims=True)
    loss = np.mean(np.sum(z_exp, axis=-1, keepdims=True))
    dzLast = z_probability - z_true
    return loss, dzLast
    

In [4]:
import numpy as np

a = [[1,2],[2,2]]
b = np.square(a)+1
print(np.square(a)+1)
print(np.sqrt(b))
print(a/b)

[[2 5]
 [5 5]]
[[1.41421356 2.23606798]
 [2.23606798 2.23606798]]
[[0.5 0.4]
 [0.4 0.4]]
